#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Time    : 2018/5/28 11:24
# @Author  : Kaiwen Xue
# @File    : cuid_summary.py
# @Software: PyCharm


def cuid_summary(file_name):
    """
    Split a txt file into three files by relationship. Use set to avoid duplicated data.
    :param file_name: txt file name
    :return: three txt file and the total number of duplicated data of each file.
    """
    file = open(file_name)
    social_lst = list()
    social_set = set()
    family_lst = list()
    family_set = set()
    colleague_lst = list()
    colleague_set = set()

    for lines in file:
        temp_list = lines.split('\t')
        family = temp_list[1]
        colleague = temp_list[2]
        social = temp_list[3]
        if family != 'None':
            family = family[1:]
            family = family[:-1]
            family = family.split(', ')
            for cuid in family:
                family_lst.append(cuid)
                family_set.add(cuid)

        if colleague != 'None':
            colleague = colleague[1:]
            colleague = colleague[:-1]
            colleague = colleague.split(', ')
            for cuid in colleague:
                colleague_lst.append(cuid)
                colleague_set.add(cuid)

        if social != 'None':
            social = social[1:]
            social = social[:-1]
            social = social.split(', ')
            for cuid in social:
                social_lst.append(cuid)
                social_set.add(cuid)

    f = open(file_name[:-4] + '_' + 'family.txt', 'w')
    for data in family_set:
        f.write(data + '\n')
    f.close()
    print(file_name[:-4], len(family_lst), len(family_set), len(family_lst) - len(family_set))

    f = open(file_name[:-4] + '_' + 'colleague.txt', 'w')
    for data in colleague_set:
        f.write(data + '\n')
    f.close()
    print(file_name[:-4], len(colleague_lst), len(colleague_set), len(colleague_lst) - len(colleague_set))

    f = open(file_name[:-4] + '_' + 'social.txt', 'w')
    for data in social_set:
        f.write(data + '\n')
    f.close()
    print(file_name[:-4], len(social_lst), len(social_set), len(social_lst) - len(social_set))


if __name__ == '__main__':
    file_name = input('Input file name: ')
    cuid_summary(file_name + '.txt')
