#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Time    : 2018/5/25 16:48
# @Author  : Kaiwen Xue
# @File    : poi_summary.py
# @Software: PyCharm
import csv
from time import time


def poi_summary(file_name):
    """
    Read and split text file line by line.
    Store the second object(POI) as key, the third object(UV) as value in a dictionary to calculate the total UV of each POI
    Sort the dictionary by value and convert it to list
    :param file_name: input the file name
    :return: a sorted result list
    """
    file = open(file_name)
    result_dic = {}

    for lines in file:
        temp_list = lines.split('\t')
        result_dic[temp_list[1]] = int(temp_list[2]) + result_dic.get(temp_list[1], 0)

    return sorted(result_dic.items(), key=lambda x: x[1], reverse=True)


def csv_file_generator(result_lst):
    """
    Write the result list to a csv file.
    :param result_lst: list created by poi_summary() function
    :return: No return, a csv file has been generatred
    """
    csvfile = open(file_name + '.csv', 'w')
    writer = csv.writer(csvfile)
    writer.writerow(['TAG', 'UV总数'])

    for items in result_lst:
        writer.writerow([items[0], items[1]])

    csvfile.close()


if __name__ == '__main__':
    print('==============================Script running==============================\n')
    start = time()

    file_name = input('Input the file name: ')
    csv_file_generator(poi_summary(file_name + '.txt'))

    ends = time()
    print('\n\n\t\t\t\t\t\t\tRunning time:', str(round(ends - start, 2)) + 's')
    print('\n==================================Ends==================================\n')